name = "SARISA"
uuid = "58f82e9d-32ac-40a9-8a46-a7c0badfaf21"
authors = ["Louis Dressel and Mykel Kochenderfer <mykel@stanford.edu>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
